Repository idea2app/idea2app.github.io, pull requests merged in 2025-05, with the labels that each got.

#77 [refactor] make GitHub & Lark API clearer & safer with Koa 2 & Next-SSR-middleware 0.10
  .npmrc
  components/Client/Partner.tsx
  components/Icon.tsx
  components/LarkImage.tsx
  components/PageHead.tsx
  eslint.config.ts
  instrumentation.ts
  models/Base.ts
  models/Client.ts
  models/Member.ts
  models/Project.ts
  models/Repository.ts
  models/configuration.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/GitHub/[...slug].ts
  pages/api/GitHub/core.ts
  pages/api/Lark/bitable/v1/[...slug].ts
  pages/api/Lark/core.ts
  pages/api/Lark/file/[id].ts
  pages/api/core.ts
  pages/api/crawler/task.ts
  pnpm-lock.yaml
Labels: enhancement, feature

#78 [add] GitHub-reward issue model, card & page
  components/Git/Issue/Card.tsx
  components/Icon.tsx
  components/Layout/MainNavigator.tsx
  components/Member/Card.tsx
  models/Base.ts
  models/Issue.ts
  models/Repository.ts
  models/configuration.ts
  next.config.ts
  package.json
  pages/_document.tsx
  pages/api/GitHub/core.ts
  pages/project/reward/issue.tsx
  pnpm-lock.yaml
Labels: feature

#79 [refactor] isolate Internationalization data with MobX-i18n 0.7 & React context
  .env
  README.md
  components/Git/Card.tsx
  components/Layout/MainNavigator.tsx
  components/Layout/ScrollListPage.tsx
  components/Layout/Section.tsx
  components/NotFoundCard.tsx
  models/Base.ts
  models/Translation.ts
  models/configuration.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/_error.tsx
  pages/api/core.ts
  pages/api/crawler/task.ts
  pages/api/home.ts
  pages/index.tsx
  pages/member/[nickname].tsx
  pages/member/index.tsx
  pages/open-source.tsx
  pages/project/[id].tsx
  pages/project/index.tsx
  pages/project/reward/issue.tsx
  pages/requirement/[title].tsx
  pages/requirement/index.tsx
  pnpm-lock.yaml
Labels: feature

#75 [add] Enhance PageHead component with Open Graph and Twitter meta tags; [add] robots.txt and sitemap.xml for SEO optimization
  components/PageHead.tsx
  models/configuration.ts
  pages/_document.tsx
  public/robots.txt
  public/sitemap.xml
Labels: enhancement
